"""Learn the fixed Novice AE map from local environment rollouts.

This script runs on the GCP Workbench, where `til_environment` is installed.
It observes many random Novice rounds, accumulates visible wall/destructible
edges through AEManager's normal parser, and writes `ae/src/fixed_map.py`.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = Path(__file__).resolve().parent / "src"
sys.path.insert(0, str(SRC))

from ae_manager import AEManager  # noqa: E402


def _jsonable_observation(observation: dict) -> dict:
    return {
        key: value if type(value) in (int, float) else value.tolist()
        for key, value in observation.items()
    }


def _edge_literal(edge) -> str:
    (ax, ay), (bx, by) = edge
    return f"(({ax}, {ay}), ({bx}, {by}))"


def main() -> None:
    from til_environment import bomberman_env
    from til_environment.config import default_config

    rounds = int(os.getenv("AE_MAP_ROUNDS", "80"))
    cfg = default_config()
    cfg.env.novice = True
    env = bomberman_env.basic_env(env_wrappers=[], cfg=cfg)
    manager = AEManager()

    for _round in range(rounds):
        env.reset()
        for agent in env.agent_iter():
            observation, _reward, termination, truncation, _info = env.last()
            if not termination and not truncation:
                obs = _jsonable_observation(observation)
                manager._ingest_observation(obs, int(obs.get("step", 0)))
                action = env.action_space(agent).sample()
            else:
                action = None
            env.step(action)

    env.close()

    out_path = SRC / "fixed_map.py"
    walls = sorted(manager.walls)
    destructible = sorted(manager.destructible_edges)
    out_path.write_text(
        "# Generated by ae/learn_fixed_map.py on the Novice environment.\n"
        "# Regenerate on Workbench if the official fixed map changes.\n\n"
        "FIXED_WALLS = {\n"
        + "".join(f"    {_edge_literal(edge)},\n" for edge in walls)
        + "}\n\n"
        "FIXED_DESTRUCTIBLE_EDGES = {\n"
        + "".join(f"    {_edge_literal(edge)},\n" for edge in destructible)
        + "}\n"
    )
    print(f"Wrote {out_path} with {len(walls)} walls and {len(destructible)} destructible edges")


if __name__ == "__main__":
    main()
